# Generated by Django 5.2.3 on 2025-06-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(help_text='Comma-separated list of authors', max_length=500)),
                ('conference_journal', models.CharField(help_text='Conference or Journal name', max_length=200)),
                ('year', models.IntegerField()),
                ('abstract', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='publications/')),
                ('doi_url', models.URLField(blank=True, help_text='DOI or external link')),
                ('arxiv_url', models.URLField(blank=True, help_text='ArXiv link')),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, to='portfolio.projecttag')),
            ],
            options={
                'ordering': ['-year', 'order', 'title'],
            },
        ),
    ]
